---
title: "Estructura del Proyecto"
author: "Roselyn Rojas"
date: "2026-09-01"
output: html_document
---

## CREACION

```{r}
# SE CREA LA ESTRUCTURA DE LAS CARPETAS QUE VAMOS A UTILIZAR PARA ORDEN Y FACILIDAD DE LOCALIZAR LOS ENTREGABLES

directorios <- c(
  "data/raw",
  "data/processed",
  "R",
  "docs",
  "bloque3_visualizaciones"
)

# Crear directorios
for (directorio in directorios) {
  if (!dir.exists(directorio)) {
    dir.create(
      path = directorio,
      recursive = TRUE
    )
  }
}

# Archivos fuente iniciales
archivos <- c(
  "R/00_config.R",
  "R/01_ingesta.R",
  "R/02_auditoria_calidad.R",
  "R/03_transformaciones.R",
  "R/04_metricas.R",
  "R/05_analisis_exploratorio.R",
  "R/06_ab_test.R",
  "R/07_export_powerbi.R",

  "docs/diccionario_datos.md",
  "docs/definicion_metricas.md",
  "docs/registro_uso_ia.md",

  "bloque0_auditoria.Rmd",
  "bloque1_queries.sql",
  "bloque2_decisiones.Rmd",
  "bloque3_analisis.Rmd",
  "bloque4_kpi_framework.Rmd",

  "data/raw/.gitkeep",
  "data/processed/.gitkeep",
  "bloque3_visualizaciones/.gitkeep"
)

# Crear los archivos que todavía no existen
for (archivo in archivos) {
  if (!file.exists(archivo)) {
    file.create(archivo)
  }
}

message("Estructura del proyecto creada correctamente")

```

## VALIDAR LA ESTRUCTURA 
```{r}
list.files(
  path = ".",
  recursive = TRUE,
  all.files = TRUE
)
```

